### ISSUE TITLE
Process proxies ignore interface inheritance

### ISSUE THREAD

**Issue by OlduwanSteve** [louthy/language-ext#108] opened 2016-07-16 11:52 UTC
It appears that the code which generates the process proxy only implements the direct interface and not its bases. If you use inheritance on your interfaces then the call to Process.proxy throws an exception complaining about missing implementations. e.g

```
public interface IBase
{
   void DoThing();
}

public interface IDerived : IBase
{
  void DoAnotherThing();
}

Process.proxy<IDerived>(); // This will fail
```

**Comment by louthy** [comment] 2016-07-17 16:08
@OlduwanSteve Ok, I'll investigate.  Unfortunately I can't deploy new versions at the moment, because the latest .NET Core tooling crashes when compiling the project.  I've talked to the team at Microsoft and they're unable to work out the cause.  My best bet (because they were able to compile the project) is to wait until my new machine arrives (hopefully) next week.  So for now I'd suggest flattening the interface.

**Comment by louthy** [comment] 2017-03-10 20:55
Fixed in the echo-process project.

**Closed by louthy** 2017-03-10 20:55 UTC
Labels: bug
