### ISSUE TITLE
Set<OrdA, A>.Except ignoring OrdA

### ISSUE THREAD

**Issue by OlduwanSteve** [louthy/language-ext#458] opened 2018-08-08 15:07 UTC
In the following code:

```
            var a = toSet<OrdStringOrdinalIgnoreCase, string>(new[] { "a" });
            var b = toSet<OrdStringOrdinalIgnoreCase, string>(new[] { "A" });
            var c = a.Except(b);
```

I would expect c to be empty but it's not. If both sets are the same case it works, suggesting perhaps that OrdA is not being used in this method.

**Comment by louthy** [comment] 2018-08-08 15:32
What version are you running? I know I fixed an issue in this area
recently.

**Comment by OlduwanSteve** [comment] 2018-08-08 15:35
Nuget package 3.0.20

**Comment by louthy** [comment] 2018-08-08 15:46
Fixed in `3.0.21` on nuget now

**Comment by OlduwanSteve** [comment] 2018-08-08 15:59
Thanks, it looks like `IsProperSubsetOf` might have a similar problem - you're making a distinct set of 'other' using `Set<A>`.

**Comment by louthy** [comment] 2018-08-08 16:07
It doesn't have the same bug, that was caused by the call to `IEnumerable.Contains` rather than `SetInternal.Contains`.  But it can be optimised like I did for Except to not generate a new set.

**Closed** 2018-08-08 16:38 UTC
