### ISSUE TITLE
ThunkAsync never returns Errors.Cancelled

### ISSUE THREAD

**Issue by harrhp** [louthy/language-ext#903] opened 2021-09-24 02:59 UTC
because if task has been cancelled [await](https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/Thunks/ThunkAsync.cs#L323) throws TaskCanceledException and [this line](https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/Thunks/ThunkAsync.cs#L323) is never reached. But it's maybe for the better, because if you want to handle cancellation you need to handle it once for TaskCanceledException or OperationCanceledException. And i think Errors.Cancelled probably would lose stacktrace, can't test it though.

```
static async Task Main(string[] args)
{
    var aff = Aff(() => ValueTask.FromCanceled<int>(new CancellationToken(true)));
    var fin = await aff.Run();
    var number = fin.ThrowIfFail();
    Console.WriteLine(number);
}
```

minor problem in the same method [unnecessary conversion to Exception](https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/Thunks/ThunkAsync.cs#L362)

**Comment by louthy** [comment] 2021-09-24 07:57
There’s a catch there as well, it should spot the cancellation, or at least catch any exception.  If that’s not happening I’ll take a look.  I’m fairly sure it works with cancel<RT>() which is what I’ve been using to cancel my Affs.

the reason for dual logic here is that await seems to have slightly different behaviour with ValueTask in that it won’t always throw on a failed/cancelled task (at least when I built it, it may well have been a .Net bug)

On your second point, yep that should be fixed.  I’m away for a few days, so it won’t be resolved until mid next week.

**Comment by harrhp** [comment] 2021-09-25 01:18
Yes, catch works, in example above i get TaskCanceledException as expected. 

ValueTask does need [more delicate handling than Task](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.valuetask-1?view=net-5.0#remarks). Also i noticed that ThunkAsync.Eval may use [AsTask](https://github.com/louthy/language-ext/blob/190c32abc821091acf57e38625a5a63596128a85/LanguageExt.Core/Thunks/ThunkAsync.cs#L331) after [await](https://github.com/louthy/language-ext/blob/190c32abc821091acf57e38625a5a63596128a85/LanguageExt.Core/Thunks/ThunkAsync.cs#L307) which results in undefined behaviour as described in msdn link and in more details [here](https://github.com/dotnet/runtime/issues/25182). But AsTask call should not be reachabale, unless it's the situation you've described, but i don't know how to reproduce it, so can't investigate why it happens

**Comment by louthy** [comment] 2021-09-27 18:21
> ValueTask does need more delicate handling than Task

I remember writing this and seeing the code carry on after an `await` even when the containing task was failed/cancelled.  I thought I was going mad at the time, but it happened, hence why I had that extra defensive code below.  I can't now reproduce it, so either it was a .NET bug that has since been fixed, or I was in fact going mad! It definitely made me slightly wary of trusting `ValueTask`.

I'll need to get some unit tests in to confirm this completely, but it's fixed to how it was originally!

**Closed by louthy** 2021-09-27 18:21 UTC
