### ISSUE TITLE
Visual Studio Debugger Exception handling: Continue when Unhandled in User Code vs Try / TryOption

### ISSUE THREAD

**Issue by StefanBertels** [louthy/language-ext#401] opened 2018-04-12 11:39 UTC
Maybe I'm doing something wrong, but I stumbled on this Debugger behaviour:

```
var x = LanguageExt.Prelude.Try<string>(() => LanguageExt.Prelude.failwith<string>("test"));
x.Match(Succ: Console.WriteLine, Fail: Console.Error.WriteLine);
```
(tested with LanguageExt stable and LanguageExt beta)

Seems like default Visual Studio Debug/Exception settings will let the debugger break at `failwith` because the Exception is "unhandled in user code". 

This only occurs if Debug setting "Enable Just My Code" is checked (AFAIK default) and there is no "Additional Action" defined in the specific Exception (see Exception Settings Windows => context menu =>"Continue when unhandled in user code") -- which AFAIK is default, too.

Does this mean: Try will always cause Debugger to stop when exception case occurs in Visual Studio default settings?

Additional note: https://docs.microsoft.com/en-us/visualstudio/debugger/managing-exceptions-with-the-debugger says that libs with debugging info (pdb) are regarded "My Code" . So if we think about how we could disable this behaviour for LanguageExt that might be one way.

Any other ideas / hints?

**Comment by louthy** [comment] 2018-04-12 13:06
Exceptions don't go away with Try and if you're running the debugger then
it will pause on all exceptions, that's just a sad fact of life, whether or
not you're inside a try/catch block or not.  It's annoyed me in the past
too.  This isn't anything to do with lang-ext, you're not running lang-ext
code at the point of the exception, you're running your code.  I'd suggest
posting the issue to the Visual Studio forums if you want something done
about it.

**Comment by StefanBertels** [comment] 2018-04-12 14:54
That's not entirely correct. The following old-school version is not affected:

```
try
{
    var x = LanguageExt.Prelude.failwith<string>("test");
    Console.WriteLine(x);
}
catch (Exception ex)
{
    Console.Error.WriteLine(ex);
}
```

It doesn't help to add some outer try-catch around my original code above.
The issue occurs if the exception occurs in or passes my code and gets catched in external code (like Try).

Yes, this is not an issue of LanguageExt. But LanguageExt suffers from this behaviour.

Some special CLR exceptions are by default excluded from this behaviour (see VS Exception Settings).


I will post this to Visual Studio team because I think there is a need to disable this behaviour for someting like Try. From my point of view it doesn't make sense to force every developer to change their VS preferences just to not be annoyed.

Seems like one reason for this crazy default is that e.g. ASP.NET applications would catch errors in framework and just give HTTP Status 500 -- making debugging bad. 

Seems like a debug build of external libs is seen as  "My code". Seems like this means (pdb and) disabled optimization :-/


One reason why I added this issue is to maybe find a better workaround and at least document this behaviour. We stumbled upon this because I had "Just My code" disabled (everything working) and a work mate with a clean VS installation reported that Try is not working as expected.

**Comment by louthy** [comment] 2018-04-12 14:57
Closing, as there's nothing that I know of that I can do in code to affect Visual Studio.

**Closed by louthy** 2018-04-12 14:57 UTC

**Comment by bender2k14** [comment] 2018-04-12 15:30
> Seems like default Visual Studio Debug/Exception settings will let the debugger break at failwith because the Exception is "unhandled in user code".

This is not how it behaves for me.  Specifically, consider this test.

```
using Xunit;
using Xunit.Abstractions;
using static LanguageExt.Prelude;

namespace LanguageExtTests
{
    public class TestClass
    {
        private ITestOutputHelper _testOutputHelper;

        public TestClass(ITestOutputHelper testOutputHelper) =>
            _testOutputHelper = testOutputHelper;

        [Fact]
        public void OptionalNumericAppend()
        {
            var x = Try(() => failwith<string>("test"));
            x.Match(Succ: _testOutputHelper.WriteLine, Fail: e => _testOutputHelper.WriteLine(e.Message));
        }

    }
}
```

Of course the test passes (and outputs "test"), but that is not the issue.  The issue is the following.

### If the test is run in debug mode, does Visual Studio break (because an exception is thrown)?

Here is how this behaves for me.  When I run the test in debug mode with the default exception settings...

![screenshot 2018-04-12 10 23 39](https://user-images.githubusercontent.com/34664007/38687175-a393db66-3e3b-11e8-9b75-75cff21ea1bc.png)

...then Visual Studio does not break anywhere, as I expect.  If I change the exception settings to break on all "Common Language Runtime Exceptions"...

![screenshot 2018-04-12 10 25 10](https://user-images.githubusercontent.com/34664007/38687242-cfb3a0c8-3e3b-11e8-9fda-fb49dcba99f9.png)

...then Visual Studio breaks _inside_ `failwith` when it `throws`, also as I expect.

> the debugger break at `failwith`

I am unaware of any way to cause Visual Studio to break _at_ `failwith` (instead of _inside_ it).

**Comment by StefanBertels** [comment] 2018-04-12 18:25
Hi @bender2k14,

Might be that you have "Just My Code" disabled because I don't see this extra column in your screenshot:

![image](https://user-images.githubusercontent.com/3862727/38696366-37937b66-3e8f-11e8-895c-4f029c17b3c2.png)

This picture shows my actual settings (everything works fine) but these are not defaults (click "Restore Defaults").

Can you check your settings in VS: Tools => Options => Debugging => General:

![image](https://user-images.githubusercontent.com/3862727/38696448-778ab66c-3e8f-11e8-8d0c-9e66955fff63.png)

**Comment by bender2k14** [comment] 2018-04-12 19:44
You previous comment makes me think that you think that

1. "Tools => Options => Debugging => General => Enable Just My Code" and
2. "Exception Settings => Common Language Runtime Exceptions => right-click menu => Continue When Unhandled In User Code"

are the same setting.  For me, they are not the same setting.  In particular, if (1) is unchecked, then (2) doesn't exist ("Continue When Unhandled In User Code" is not longer in the right-click menu).

Also for me, the behavior is the same for all three possible settings of these two checkboxes.  Namely, Visual Studio does not break when that test is run in debug mode.

**Comment by StefanBertels** [comment] 2018-04-12 20:58
No, I don't thin that. 

There are two settings. 

1. "Enable Just My Code" is a general setting which let's the debugger make a difference between "my" code (source code + debug-libraries) and (optimized) libaries. 

2. The difference depends on Exception settings, especially on "Continue When Unhandled" option that is disabled by default for most Exceptions, including "Exception".


Therefore the behaviour is correct and Visual Studio documentation matches this.  I just verified it with a third machine, so everything fits together here.

But I think it is not a good default or at least VS default settings are bad when using Try. At least if you want to debug your code and expect that your debugger only stops when your compiled program would crash (= completely unhandled exception).

I wonder how you can have a different behaviour with default settings on your machine. I'm interested in the difference as it might help to find a workaround (other than setting every developer machine to IMO reasonable non-default settings).

I just verified that my debugger stops if I put code into a XUnit test and run that in Debug mode (xunit visualstudio runner). Here's my complete project:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LanguageExt.Core" Version="2.1.32" />
    <PackageReference Include="xunit" Version="2.3.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
  </ItemGroup>

</Project>
```

Program.cs
```
using System;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            var x = LanguageExt.Prelude.Try<string>(() => LanguageExt.Prelude.failwith<string>("test"));
            x.Match(Succ: Console.WriteLine, Fail: Console.Error.WriteLine);
        }
    }
}
```

Test.cs
```
using Xunit;

namespace ConsoleApp2
{
    public class Test
    {
        [Fact]
        void PassOrBreak()
        {
            var x = LanguageExt.Prelude.Try<string>(() => LanguageExt.Prelude.failwith<string>("test"));
            var result = x.Match(Succ: _ => 1, Fail: _ => -1);
            Assert.Equal(-1, result);
        }
    }
}
```

If this does not stop in debug mode on your machine, could you attach your debug settings (Tools => Options => Debug => General)?

**Comment by bender2k14** [comment] 2018-04-13 13:29
I still have the same behavior running your test (i.e. never breaks when running in debug mode) using both my "current" debug settings (see requested screenshot below) as well as the default Visual Studio settings called "General".

![screenshot 2018-04-13 08 27 40](https://user-images.githubusercontent.com/34664007/38737408-b6c77738-3ef4-11e8-962d-424f5d1e6744.png)

**Comment by tqk2811** [comment] 2025-04-25 11:04
My case: Disable -> close vs -> enable.


-Disable Just My Code, Exception Settings > Restore Defaults. 
-Close VS
-Enable Just My Code, Exception Settings >  Common Language Runtime Exceptions => right-click menu => Continue When Unhandled In User Code"
