### ISSUE TITLE
Implicit conversion of Some / Option SubTypes

### ISSUE THREAD

**Issue by donners77** [louthy/language-ext#22] opened 2015-06-12 10:29 UTC
Hi.

I am occasionally running into an issue when I need to pass ``Some<TSuper>`` into a method/constructor as a parameter but what I have at hand is ``Some<T>`` where ``T : TSuper``.

The C# 5 compiler doesn't seem to implicitly convert between the wrapped types, but makes me manually unwrap and then re-wrap...

e.g. ``new Foo(new Some((TSuperType)bar.Value))``

Is there a nicer way to do this?

**Comment by louthy** [comment] 2015-06-12 15:21
The problem is that `struct` doesn't support [covariance](https://msdn.microsoft.com/en-gb/library/ee207183.aspx).  So there's no easy fix for this.  

For example this below won't work:

```C#
        public static void Foo(Some<IEnumerable<string>> val)
        {
        }

        public void SomeCastTest1()
        {
            var some = new Some<List<string>>(new List<string>() { "a", "b", "c" });
            Foo(some);
        }
```
But this will:

```C#
        public void SomeCastTest2()
        {
            Foo(new List<string>() { "a", "b", "c" });
        }
```

So you could either not pass `Some<T>` into functions, and only use them to protect function parameters.  Or, you could manually extract the `.Value`

```C#
        public void SomeCastTes3()
        {
            var some = new Some<List<string>>(new List<string>() { "a", "b", "c" });
            Foo(some.Value);
        }
```

Or you could implement your own cast method:

```C#
        public static Some<R> Cast<T, R>(Some<T> value) where T : R =>
            value.Value;
```

The problem with that is the type-inference system is poor in c# so you end up with lots of type boilerplate:

```C#
            Foo(Cast<List<string>,IEnumerable<string>>(some));
```

So unfortunately there aren't any perfect solutions here.

**Comment by donners77** [comment] 2015-06-13 01:04
Hi.

I think I've tried what you suggested...

        public void SomeCastTes3()
        {
            var some = new Some<List<string>>(new List<string>() { "a", "b", "c" });
            Foo(some.Value);
        }

But it doesn't seem to be acceptable to the compiler...

![covariance issue example](https://cloud.githubusercontent.com/assets/5105950/8142308/c84bd8b4-11bb-11e5-9262-ee4a07a16565.jpg)

**Comment by donners77** [comment] 2015-06-13 02:41
I think I may have found a compromise solution...

In Prelude ``public static Some<T> ToSome<T>(this T value) { return Create(value); }``

Then I can do ``filterMut.Value.ToSome<IFilter<T>>()``

**Comment by donners77** [comment] 2015-06-13 03:08
The implicit type conversion also seems to fail at times when no unwrapping is required, e.g...

![similar issue example](https://cloud.githubusercontent.com/assets/5105950/8142768/f45728ee-11cc-11e5-85db-dc293df8c1ef.jpg)

``ToImmutable()`` returns an ``IFilterIm<T>`` but the compiler complains about implicitly converting this to a ``Some<IFilterIm<T>>``

I wonder if this is some limitation related to Generics?

**Comment by donners77** [comment] 2015-07-26 02:17
Hi. Wondering if you have any further thoughts on this?

**Comment by louthy** [comment] 2015-07-28 12:26
Hi @donners77 ,

If I'm honest I haven't spent too much time thinking about it, no.  I'd be slightly reluctant to add `ToSome()` as an extension method to `T`, mainly because it then pollutes the intellisense for everything, and I think that's a bit too much of an intrusion by a library, especially for those who don't use the `Some<T>` type, but are using other aspects of the library.

Obviously `ToSome()` works because it's not doing implicit type casting of a `T` to a `Some<T>`, it's passing a `T` to the constructor of `Some<T>` where the normal implicit type casting can happen.  Until `struct` can do covariant implicit type-casting I think you're stuck with `ToSome()` as a solution.  You'll just need to create it yourself.

I guess one way could be to put the extension method into its own namespace.  Perhaps `LanguageExt.SomeHelp`.  That would mean you could opt into it.  I guess I'd be amenable to this idea.  What do you think?

**Comment by donners77** [comment] 2015-08-02 04:18
Hi. I don't mind. Happy to just implement it for myself. Happy for it to be in the namespace you suggested if you think other people will need it.

**Comment by louthy** [comment] 2015-08-03 13:35
Cool, I've now added this to the `LanguageExt.SomeHelp` namespace.  Thanks for the suggestion :)

**Closed** 2015-08-09 02:33 UTC
Labels: enhancement, question
